on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Folder names before'
        run: ls

      - uses: actions/checkout@v3

      - name: 'Folder names after'
        run: ls
